### PR TITLE
SE refactoring

### PR DESCRIPTION
**Pull request by tvsonar**

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. INFO [ControlFlowGraphBuilder.cs#L649](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/83119dd6bc9d89b8819e351926ea842247126c80/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L649): Complete the task associated to this "TODO" comment. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1135)

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. INFO [ControlFlowGraphBuilder.cs#L649](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/22d0608f4b10613e7984543c4e365e8b815ec413/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L649): Complete the task associated to this "TODO" comment. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1135)

**Comment by tvsonar** [comment]
@benzonico I made some refactoring to separate the generic exploded graph walking from the stack push/pops. In the end it became a generic class that does the walk and the C# specific. The same structure as what we have for CFG building and LVA.

**Comment by benzonico** [comment]
LGTM.

**Pull request merged**
