### PR TITLE
Removing public const fields by making them internal, and defining fr…

### PR DESCRIPTION
**Pull request by tvsonar**
…iend assemblies

### CODE REVIEW

**Comment by tvsonar** [comment]
Note to self: the release process should be modified to build with `msbuild /t:rebuild /p:Configuration=Release /p:defineConstants=SignAssembly /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=...`

**Comment by tvsonar** [comment]
Note to self: `KnownTypes` can be made internal, the CFG common part can be moved to its proper location.

**Comment by SonarTech** [comment]
SonarQube analysis reported 20 issues
* MAJOR 19 major
* INFO 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ControlFlowGraphBuilder.cs#L96](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L96): 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)' has a cyclomatic complexity of 28. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L155](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L155): 'statement', a parameter, is cast to type 'YieldStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L178](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L178): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L183](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L183): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L201](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L201): 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)' has a cyclomatic complexity of 42. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L224](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L224): 'expression', a parameter, is cast to type 'AssignmentExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L319](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L319): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L330](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L330): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L334](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L334): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L361](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/849154f04f244a0fcf66f1e3deca49c603dc2143/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L361): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)

**Comment by SonarTech** [comment]
SonarQube analysis reported 20 issues
* MAJOR 19 major
* INFO 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ControlFlowGraphBuilder.cs#L96](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L96): 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)' has a cyclomatic complexity of 28. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L155](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L155): 'statement', a parameter, is cast to type 'YieldStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L178](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L178): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L183](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L183): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L201](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L201): 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)' has a cyclomatic complexity of 42. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L224](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L224): 'expression', a parameter, is cast to type 'AssignmentExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L319](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L319): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L330](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L330): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L334](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L334): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L361](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/f92bd0cc9cb5302f8dcdaf9ab67ec5188df549e4/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L361): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)

**Comment by SonarTech** [comment]
SonarQube analysis reported 20 issues
* MAJOR 19 major
* INFO 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ControlFlowGraphBuilder.cs#L96](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L96): 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)' has a cyclomatic complexity of 28. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L155](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L155): 'statement', a parameter, is cast to type 'YieldStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L178](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L178): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L183](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L183): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L201](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L201): 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)' has a cyclomatic complexity of 42. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L224](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L224): 'expression', a parameter, is cast to type 'AssignmentExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L319](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L319): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L330](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L330): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L334](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L334): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L361](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/0c0dba21791181448d6dfde8afd1f6b7e225191c/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L361): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)

**Comment by SonarTech** [comment]
SonarQube analysis reported 22 issues
* MAJOR 21 major
* INFO 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ControlFlowGraphBuilder.cs#L96](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L96): 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)' has a cyclomatic complexity of 28. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L155](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L155): 'statement', a parameter, is cast to type 'YieldStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L178](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L178): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L183](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L183): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L201](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L201): 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)' has a cyclomatic complexity of 42. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L224](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L224): 'expression', a parameter, is cast to type 'AssignmentExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L319](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L319): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L330](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L330): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L334](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L334): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L361](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/2686882867ecac4b3a5b1cac7b4446f13985eb27/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L361): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)

**Comment by SonarTech** [comment]
SonarQube analysis reported 22 issues
* MAJOR 21 major
* INFO 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ControlFlowGraphBuilder.cs#L96](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L96): 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)' has a cyclomatic complexity of 28. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L155](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L155): 'statement', a parameter, is cast to type 'YieldStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L178](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L178): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L183](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L183): 'statement', a parameter, is cast to type 'GotoStatementSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildStatement(StatementSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L201](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L201): 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)' has a cyclomatic complexity of 42. Rewrite or refactor the method to reduce complexity to 25. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3AAvoidExcessiveComplexity)
1. MAJOR [ControlFlowGraphBuilder.cs#L224](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L224): 'expression', a parameter, is cast to type 'AssignmentExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L319](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L319): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)
1. MAJOR [ControlFlowGraphBuilder.cs#L330](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L330): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L334](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L334): Either merge this case with the identical one on line "293" or change one of the implementations. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS1871)
1. MAJOR [ControlFlowGraphBuilder.cs#L361](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp/blob/7c2130e4d4f75b4a60bc8b9c280a024daa0da8d8/src/SonarLint.CSharp/Helpers/ControlFlowGraph/ControlFlowGraphBuilder.cs#L361): 'expression', a parameter, is cast to type 'BinaryExpressionSyntax' multiple times in method 'ControlFlowGraphBuilder.BuildExpression(ExpressionSyntax)'. Cache the result of the 'as' operator or direct cast in order to eliminate the redundant castclass instruction. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=fxcop%3ADoNotCastUnnecessarily)

**Pull request merged**
